import { jsPDF } from "jspdf";

/* Brand palette (RGB) for the PDF — kept independent of the live theme so
   the exported report always looks the same regardless of dark/light mode. */
const INK = [26, 16, 4];
const MUTED = [120, 105, 88];
const FIRE = [255, 107, 0];
const LINE = [232, 222, 208];

const CAT_LABELS = {
  ats: "ATS Compatibility",
  skills: "Skills",
  projects: "Projects",
  experience: "Experience",
  impact: "Impact",
};

function scoreColor(v) {
  if (v >= 75) return [0, 168, 112];   // emerald
  if (v >= 50) return [223, 158, 0];   // amber
  return [220, 79, 0];                 // fire
}

/**
 * Build and download a polished, vector PDF of the roast report.
 * Everything is drawn programmatically so it renders crisply at any zoom
 * and avoids html2canvas colour-function pitfalls.
 */
export function downloadReportPdf({ verdict, verdictDesc, overall, categories, sections, filename = "resume" }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = 0;

  // ── Header band ──
  doc.setFillColor(...INK);
  doc.rect(0, 0, W, 96, "F");
  doc.setTextColor(255, 107, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("MACOOSTUDY REPORT", M, 50);
  doc.setTextColor(220, 210, 196);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("AI Resume Report  ·  macoostudy.info", M, 70);
  // Overall score badge in header
  const badgeColor = scoreColor(overall);
  doc.setFillColor(...badgeColor);
  doc.circle(W - M - 26, 48, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(String(overall), W - M - 26, 52, { align: "center" });
  doc.setFontSize(7);
  doc.text("/100", W - M - 26, 64, { align: "center" });

  y = 132;

  // ── Verdict ──
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("VERDICT", M, y);
  y += 18;
  doc.setTextColor(...INK);
  doc.setFontSize(16);
  doc.text(stripEmoji(verdict) || "Entry Level", M, y);
  if (verdictDesc) {
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.text(verdictDesc, M, y);
  }
  y += 28;

  // ── Category bars ──
  doc.setDrawColor(...LINE);
  doc.line(M, y, W - M, y);
  y += 26;
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("CATEGORY BREAKDOWN", M, y);
  y += 18;

  const barX = M + 130;
  const barW = W - M - barX - 40;
  Object.entries(categories || {}).forEach(([key, val]) => {
    const v = Math.max(0, Math.min(100, val || 0));
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    doc.text(CAT_LABELS[key] || key, M, y + 9);
    // track
    doc.setFillColor(...LINE);
    doc.roundedRect(barX, y, barW, 9, 4.5, 4.5, "F");
    // fill
    doc.setFillColor(...scoreColor(v));
    doc.roundedRect(barX, y, Math.max(9, (barW * v) / 100), 9, 4.5, 4.5, "F");
    // value
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    doc.text(String(v), W - M, y + 9, { align: "right" });
    y += 24;
  });

  y += 8;
  doc.setDrawColor(...LINE);
  doc.line(M, y, W - M, y);
  y += 26;

  // ── Roast sections ──
  (sections || []).forEach(sec => {
    const heading = sec.title || sec.key || "";
    const body = (sec.content || "").replace(/^[^\n]*\n?/, sec.title ? "$&" : "");
    const lines = doc.splitTextToSize(stripEmoji(sec.content || ""), W - M * 2);
    const blockH = 22 + lines.length * 13;
    if (y + blockH > H - 60) { doc.addPage(); y = 56; }

    doc.setFillColor(...FIRE);
    doc.rect(M, y - 9, 3, blockH - 6, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...INK);
    doc.text((heading || "Feedback").toUpperCase(), M + 12, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 48, 34);
    lines.forEach(line => {
      if (y > H - 56) { doc.addPage(); y = 56; }
      doc.text(line, M + 12, y);
      y += 13;
    });
    y += 16;
  });

  // ── Footer on every page ──
  const pages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setDrawColor(...LINE);
    doc.line(M, H - 40, W - M, H - 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by Macoostudy · macoostudy.info", M, H - 26);
    doc.text(`Page ${p} of ${pages}`, W - M, H - 26, { align: "right" });
  }

  const safe = String(filename).replace(/\.pdf$/i, "").replace(/[^\w-]+/g, "_").slice(0, 40);
  doc.save(`roast-report-${safe || "resume"}.pdf`);
}

/**
 * Generic, clean, paginated text PDF with the same branded header/footer as
 * the roast report — so every tool exports a consistent-looking PDF (not .txt).
 * `sections` = [{ heading, lines: string[] }] or [{ heading, body: string }].
 */
export function downloadTextPdf({ title, subtitle, sections = [], filename = "report" }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = 0;

  // Header band
  doc.setFillColor(...INK);
  doc.rect(0, 0, W, 84, "F");
  doc.setTextColor(255, 107, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(stripEmoji(title) || "Report", M, 44);
  doc.setTextColor(220, 210, 196);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(stripEmoji(subtitle) || "Macoostudy · macoostudy.info", M, 64);

  y = 116;
  sections.forEach(sec => {
    const lines = sec.lines || (sec.body ? doc.splitTextToSize(stripEmoji(sec.body), W - M * 2) : []);
    if (y + 30 > H - 60) { doc.addPage(); y = 56; }
    doc.setFillColor(...FIRE);
    doc.rect(M, y - 9, 3, 14, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...INK);
    doc.text((sec.heading || "").toUpperCase(), M + 12, y);
    y += 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 48, 34);
    lines.forEach(raw => {
      const wrapped = doc.splitTextToSize(stripEmoji(String(raw)), W - M * 2 - 12);
      wrapped.forEach(line => {
        if (y > H - 56) { doc.addPage(); y = 56; }
        doc.text(line, M + 12, y);
        y += 13;
      });
    });
    y += 16;
  });

  const pages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setDrawColor(...LINE);
    doc.line(M, H - 40, W - M, H - 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by Macoostudy · macoostudy.info", M, H - 26);
    doc.text(`Page ${p} of ${pages}`, W - M, H - 26, { align: "right" });
  }

  const safe = String(filename).replace(/\.pdf$/i, "").replace(/[^\w-]+/g, "_").slice(0, 40);
  doc.save(`${safe || "report"}.pdf`);
}

/* jsPDF's core fonts can't render emoji glyphs — strip them for clean output. */
function stripEmoji(str = "") {
  return str
    .replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}️]/gu, "")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}
